# Generated by Django 4.2.3 on 2023-08-01 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendslist',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendslist',
            name='pending_follow_requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='pending_follow_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
