# Generated by Django 4.2.3 on 2023-08-01 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_friendslist_follows_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_status', models.IntegerField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'Pending'), (3, 'Confused'), (4, 'Blocked')])),
                ('friend_status_added', models.DateTimeField(blank=True, null=True)),
                ('friend_status_updated', models.DateTimeField(blank=True, null=True)),
                ('followers', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FriendsList',
        ),
    ]
