# Generated by Django 4.2.3 on 2023-08-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_friendmap_delete_friendslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendmap',
            name='followers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='friend_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
